music.setTempo(120)
for (let index = 0; index < 2; index++) {
    music.playTone(262, music.beat(BeatFraction.Quarter))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    music.playTone(262, music.beat(BeatFraction.Double))
    basic.pause(50)
}
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(50)
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(25)
music.playTone(494, music.beat(BeatFraction.Whole))
basic.pause(25)
music.playTone(370, music.beat(BeatFraction.Quarter))
basic.pause(25)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(349, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(294, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(262, music.beat(BeatFraction.Eighth))
music.playTone(294, music.beat(BeatFraction.Eighth))
music.playTone(262, music.beat(BeatFraction.Eighth))
music.playTone(294, music.beat(BeatFraction.Eighth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(247, music.beat(BeatFraction.Quarter))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(196, music.beat(BeatFraction.Eighth))
music.playTone(196, music.beat(BeatFraction.Eighth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(25)
music.playTone(494, music.beat(BeatFraction.Whole))
basic.pause(25)
music.playTone(370, music.beat(BeatFraction.Quarter))
basic.pause(25)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(392, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(349, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(294, music.beat(BeatFraction.Half))
basic.pause(25)
music.playTone(262, music.beat(BeatFraction.Eighth))
music.playTone(294, music.beat(BeatFraction.Eighth))
music.playTone(262, music.beat(BeatFraction.Eighth))
music.playTone(294, music.beat(BeatFraction.Eighth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(247, music.beat(BeatFraction.Quarter))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.playTone(262, music.beat(BeatFraction.Double))
